//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace di.examen.nov._2021.bis.Backend.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aerolineasEntities : DbContext
    {
        public aerolineasEntities()
            : base("name=aerolineasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<avion> avion { get; set; }
        public virtual DbSet<ciudades> ciudades { get; set; }
        public virtual DbSet<personal> personal { get; set; }
        public virtual DbSet<revisiones> revisiones { get; set; }
        public virtual DbSet<tipo> tipo { get; set; }
        public virtual DbSet<vuelos> vuelos { get; set; }
    }
}
