//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace di.examen.nov._2021.bis.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vuelos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vuelos()
        {
            this.personal = new HashSet<personal>();
        }
    
        public int Codigo_Vuelo { get; set; }
        public System.DateTime Dia { get; set; }
        public System.TimeSpan duracion { get; set; }
        public Nullable<int> Reservas { get; set; }
        public string Matricula_Avion { get; set; }
        public string Codigo_Ciudad_Eixida { get; set; }
        public string Codigo_Ciudad_Arribada { get; set; }
    
        public virtual avion avion { get; set; }
        public virtual ciudades ciudades { get; set; }
        public virtual ciudades ciudades1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personal> personal { get; set; }
    }
}
